server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization?createDatabaseIfNotExist=false&serverTimezone=Europe/Bucharest
    username: root
    password: 93899389
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: sebastian.voievod@gmail.com
    password: wdymcsqbdccyhugd

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: auth-server



eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 4

label:
  form:
    title: "REGISTER"

custom:
  email:
    validationKey: "IDKWHATSHAPENING"
    salt: "SALTSALTSALTSALT" #must be 16 bytes to encryption to work
    validHours: 1