server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization?createDatabaseIfNotExist=false&serverTimezone=Europe/Bucharest
    username: root
    password: 93899389
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
  application:
    name: auth-server

